"""Mazos por faccion.

Habilidades disponibles (ver reglas.py):
  - "quema"     captura a cualquier enemigo adyacente, sin importar el valor
  - "muro"      su lado mas alto no puede ser capturado
  - "furia"     +1 a todos sus lados si toca otra carta amiga en el tablero
  - "embestida" +2 a todos sus lados si se coloca en la casilla central
"""

from reglas import Carta

GOBLINS = [
    Carta("Mordedor", 8, 4, 6, 5, bando="goblin"),
    Carta("Brujo Verde", 3, 9, 4, 7, bando="goblin", habilidad="quema"),
    Carta("Lanzasalgo", 6, 5, 9, 4, bando="goblin"),
    Carta("Saqueador", 7, 6, 3, 8, bando="goblin"),
    Carta("Rey Goblin", 10, 7, 8, 6, bando="goblin"),
    Carta("Pinchacubos", 7, 5, 6, 5, bando="goblin"),
    Carta("Corretejas", 6, 4, 8, 5, bando="goblin"),
    Carta("Chamana Gris", 5, 9, 4, 6, bando="goblin", habilidad="quema"),
    Carta("Jefe de Tropa", 8, 7, 6, 5, bando="goblin"),
    Carta("Madre Rata", 9, 8, 7, 9, bando="goblin"),
    Carta("Rascaollas", 5, 4, 8, 4, bando="goblin"),
    Carta("Mocos", 4, 5, 6, 6, bando="goblin"),
    Carta("Tirachinas", 7, 3, 6, 5, bando="goblin"),
    Carta("Robaqueso", 6, 5, 4, 7, bando="goblin"),
    Carta("Piojo", 3, 6, 7, 6, bando="goblin"),
    Carta("Lamecharcos", 5, 7, 3, 7, bando="goblin"),
    Carta("Chivato", 6, 6, 5, 5, bando="goblin"),
    Carta("Trampero", 4, 8, 4, 6, bando="goblin", habilidad="muro"),
    Carta("Apestoso", 7, 7, 5, 7, bando="goblin", habilidad="furia"),
    Carta("Revuelcabolsas", 8, 5, 7, 6, bando="goblin", habilidad="embestida"),
    Carta("Muerdeorejas", 6, 8, 6, 7, bando="goblin"),
    Carta("Saltatechos", 9, 5, 6, 8, bando="goblin", habilidad="furia"),
    Carta("Granuja", 9, 6, 8, 7, bando="goblin"),
    Carta("Plaga Verde", 10, 8, 8, 8, bando="goblin", habilidad="embestida"),
    Carta("Desguace", 9, 9, 8, 9, bando="goblin"),
]

ELFOS = [
    Carta("Arquero", 7, 5, 8, 6, bando="elfo"),
    Carta("Dama Hoja", 5, 8, 4, 9, bando="elfo"),
    Carta("Centinela", 4, 6, 10, 3, bando="elfo"),
    Carta("Sabio del Bosque", 3, 10, 5, 7, bando="elfo"),
    Carta("Elfo Real", 9, 6, 7, 8, bando="elfo"),
    Carta("Exploradora", 6, 5, 7, 6, bando="elfo"),
    Carta("Hoja Gemela", 8, 6, 5, 7, bando="elfo"),
    Carta("Archivista", 5, 9, 6, 6, bando="elfo"),
    Carta("Vengador Silvano", 9, 7, 8, 5, bando="elfo"),
    Carta("Corazon del Bosque", 10, 9, 8, 9, bando="elfo"),
    Carta("Broteluz", 4, 5, 7, 5, bando="elfo"),
    Carta("Ciervo Blanco", 6, 4, 6, 5, bando="elfo"),
    Carta("Flautista", 5, 3, 8, 5, bando="elfo"),
    Carta("Musgo Viejo", 3, 7, 5, 7, bando="elfo"),
    Carta("Arco Corto", 7, 4, 5, 6, bando="elfo"),
    Carta("Lechuza", 5, 6, 6, 5, bando="elfo"),
    Carta("Seta Cantora", 4, 8, 3, 7, bando="elfo"),
    Carta("Refugio Verde", 6, 7, 4, 5, bando="elfo", habilidad="muro"),
    Carta("Cazador de Niebla", 5, 8, 5, 8, bando="elfo", habilidad="quema"),
    Carta("Danza de Hojas", 7, 6, 8, 5, bando="elfo", habilidad="furia"),
    Carta("Arpa de Guerra", 8, 5, 7, 7, bando="elfo", habilidad="embestida"),
    Carta("Tiro Largo", 9, 6, 5, 8, bando="elfo"),
    Carta("Bosque Antiguo", 8, 9, 7, 6, bando="elfo", habilidad="furia"),
    Carta("Copa Eterna", 10, 8, 8, 8, bando="elfo"),
    Carta("Raíz del Mundo", 9, 10, 8, 9, bando="elfo", habilidad="embestida"),
]

HOMBRES_LOBO = [
    Carta("Garras de Luna", 8, 5, 6, 4, bando="hombre_lobo"),
    Carta("Mordedor Lunar", 6, 9, 4, 5, bando="hombre_lobo"),
    Carta("Aullador", 5, 7, 8, 4, bando="hombre_lobo"),
    Carta("Piel Gris", 4, 6, 9, 6, bando="hombre_lobo"),
    Carta("Alfa del Bosque", 10, 6, 8, 7, bando="hombre_lobo"),
    Carta("Cachorro", 6, 5, 5, 6, bando="hombre_lobo"),
    Carta("Rastreadora", 7, 6, 8, 4, bando="hombre_lobo"),
    Carta("Aullido", 5, 9, 6, 5, bando="hombre_lobo"),
    Carta("Colmillo Blanco", 9, 6, 7, 8, bando="hombre_lobo"),
    Carta("Madre Luna", 10, 8, 9, 8, bando="hombre_lobo"),
    Carta("Hocico", 5, 4, 7, 5, bando="hombre_lobo"),
    Carta("Pata Veloz", 7, 3, 6, 5, bando="hombre_lobo"),
    Carta("Pelaje Sucio", 4, 6, 5, 6, bando="hombre_lobo"),
    Carta("Lobezno", 6, 5, 4, 7, bando="hombre_lobo"),
    Carta("Gañido", 3, 7, 6, 6, bando="hombre_lobo"),
    Carta("Senda de Huellas", 5, 7, 4, 6, bando="hombre_lobo"),
    Carta("Diente de Leche", 4, 5, 7, 7, bando="hombre_lobo", habilidad="quema"),
    Carta("Guarida", 6, 6, 5, 5, bando="hombre_lobo", habilidad="muro"),
    Carta("Lomo Plateado", 8, 6, 6, 6, bando="hombre_lobo", habilidad="furia"),
    Carta("Caza Nocturna", 7, 7, 7, 5, bando="hombre_lobo", habilidad="embestida"),
    Carta("Fauces Abiertas", 6, 8, 7, 6, bando="hombre_lobo"),
    Carta("Manada Unida", 7, 8, 6, 7, bando="hombre_lobo", habilidad="furia"),
    Carta("Luna Llena", 9, 7, 6, 8, bando="hombre_lobo"),
    Carta("Terror del Valle", 10, 8, 8, 8, bando="hombre_lobo"),
    Carta("Eclipse de Sangre", 9, 9, 9, 8, bando="hombre_lobo"),
]

VAMPIROS = [
    Carta("Conde Nocturno", 9, 8, 7, 6, bando="vampiro"),
    Carta("Dama Carmin", 5, 9, 4, 8, bando="vampiro"),
    Carta("Murcielago", 3, 6, 10, 4, bando="vampiro"),
    Carta("Cazadora de Sangre", 7, 7, 5, 8, bando="vampiro"),
    Carta("Vastago", 6, 5, 8, 9, bando="vampiro"),
    Carta("Doncella Palida", 6, 6, 7, 5, bando="vampiro"),
    Carta("Esgrimidor", 8, 5, 6, 7, bando="vampiro"),
    Carta("Oraculo de Sangre", 5, 9, 7, 6, bando="vampiro"),
    Carta("Alas Negras", 7, 8, 9, 4, bando="vampiro"),
    Carta("Principe Rojo", 10, 9, 8, 9, bando="vampiro"),
    Carta("Siervo Pálido", 4, 5, 6, 6, bando="vampiro"),
    Carta("Rata de Cripta", 6, 3, 7, 5, bando="vampiro"),
    Carta("Novia de Niebla", 5, 4, 8, 4, bando="vampiro"),
    Carta("Mayordomo", 5, 6, 4, 7, bando="vampiro"),
    Carta("Candil Rojo", 3, 8, 5, 7, bando="vampiro", habilidad="quema"),
    Carta("Jardín de Espinas", 4, 7, 5, 6, bando="vampiro"),
    Carta("Sangre Joven", 7, 4, 5, 6, bando="vampiro"),
    Carta("Ataúd Reforzado", 5, 7, 6, 4, bando="vampiro", habilidad="muro"),
    Carta("Vals Eterno", 6, 7, 7, 6, bando="vampiro", habilidad="furia"),
    Carta("Capa Carmesí", 8, 6, 5, 7, bando="vampiro", habilidad="embestida"),
    Carta("Ansia Nocturna", 7, 6, 7, 7, bando="vampiro"),
    Carta("Beso Frío", 5, 9, 6, 8, bando="vampiro"),
    Carta("Ópera Sangrienta", 9, 7, 7, 7, bando="vampiro"),
    Carta("Medianoche Eterna", 10, 8, 9, 7, bando="vampiro"),
    Carta("Latido Final", 9, 10, 8, 8, bando="vampiro"),
]

DRAGONES = [
    Carta("Drake", 7, 6, 8, 5, bando="dragon"),
    Carta("Fuego", 5, 8, 4, 9, bando="dragon", habilidad="quema"),
    Carta("Guerrero Rojo", 8, 5, 7, 6, bando="dragon"),
    Carta("Segador Alado", 6, 7, 9, 4, bando="dragon"),
    Carta("Rey Dragon", 10, 9, 8, 8, bando="dragon"),
    Carta("Cria", 6, 5, 7, 5, bando="dragon"),
    Carta("Escupellamas", 8, 6, 5, 7, bando="dragon", habilidad="quema"),
    Carta("Cola Ferrea", 7, 7, 8, 5, bando="dragon", habilidad="muro"),
    Carta("Vuelo Rasante", 9, 6, 8, 5, bando="dragon", habilidad="embestida"),
    Carta("Reina Ceniza", 9, 10, 8, 8, bando="dragon"),
    Carta("Guijarro", 4, 5, 7, 5, bando="dragon"),
    Carta("Cola Corta", 6, 4, 6, 5, bando="dragon"),
    Carta("Nido de Ceniza", 5, 3, 8, 5, bando="dragon"),
    Carta("Escama Suelta", 3, 7, 6, 6, bando="dragon"),
    Carta("Ala Rota", 7, 4, 5, 6, bando="dragon"),
    Carta("Bostezo Ígneo", 5, 6, 6, 5, bando="dragon"),
    Carta("Charca de Lava", 4, 8, 3, 7, bando="dragon"),
    Carta("Diente Curvo", 6, 7, 4, 5, bando="dragon"),
    Carta("Vuelo en Círculo", 7, 6, 7, 6, bando="dragon", habilidad="furia"),
    Carta("Garganta Ardiente", 8, 6, 6, 6, bando="dragon", habilidad="embestida"),
    Carta("Tormenta de Escamas", 6, 8, 7, 6, bando="dragon"),
    Carta("Sombra Alada", 9, 5, 7, 7, bando="dragon", habilidad="furia"),
    Carta("Fauces del Volcán", 8, 9, 7, 6, bando="dragon"),
    Carta("Corazón de Magma", 10, 8, 8, 8, bando="dragon"),
    Carta("Fin del Cielo", 9, 10, 8, 9, bando="dragon", habilidad="embestida"),
]

HUMANOS = [
    Carta("Sargento Ferrum", 5, 7, 6, 4, bando="humano", habilidad="muro"),
    Carta("Espadachin", 8, 6, 5, 7, bando="humano"),
    Carta("Arquera de Torre", 6, 5, 9, 5, bando="humano"),
    Carta("Clerigo de la Luz", 4, 6, 5, 9, bando="humano"),
    Carta("Rey Aldric", 10, 8, 7, 8, bando="humano", habilidad="muro"),
    Carta("Escudero", 5, 6, 5, 6, bando="humano"),
    Carta("Ballestero", 7, 4, 8, 6, bando="humano"),
    Carta("Capellan de Batalla", 4, 8, 6, 7, bando="humano", habilidad="muro"),
    Carta("Caballero Andante", 8, 7, 6, 5, bando="humano", habilidad="furia"),
    Carta("Reina Isolde", 9, 9, 8, 8, bando="humano"),
    Carta("Ariete del Alba", 9, 5, 7, 6, bando="humano", habilidad="embestida"),
    Carta("Pica Corta", 6, 4, 7, 5, bando="humano"),
    Carta("Hondero", 5, 3, 8, 6, bando="humano"),
    Carta("Mozo de Fragua", 4, 7, 5, 6, bando="humano"),
    Carta("Alabardero", 7, 6, 4, 5, bando="humano"),
    Carta("Broquel", 5, 5, 7, 6, bando="humano"),
    Carta("Antorcha Viva", 4, 6, 5, 8, bando="humano", habilidad="quema"),
    Carta("Tamborilero", 6, 6, 4, 7, bando="humano"),
    Carta("Vigía del Muro", 5, 7, 4, 7, bando="humano"),
    Carta("Lanza del Alba", 8, 6, 7, 5, bando="humano", habilidad="furia"),
    Carta("Jinete Pardo", 7, 8, 6, 5, bando="humano", habilidad="embestida"),
    Carta("Arcabucero", 9, 4, 8, 6, bando="humano"),
    Carta("Estandarte Dorado", 7, 7, 6, 8, bando="humano", habilidad="furia"),
    Carta("Amanecer Blindado", 10, 9, 8, 7, bando="humano", habilidad="embestida"),
    Carta("Sol Naciente", 9, 9, 9, 8, bando="humano"),
]

ORCOS = [
    Carta("Bruto Rasgador", 8, 5, 7, 4, bando="orco", habilidad="furia"),
    Carta("Chaman Karzh", 4, 9, 5, 7, bando="orco", habilidad="quema"),
    Carta("Lancero Gruano", 6, 7, 8, 5, bando="orco"),
    Carta("Trol de Ceniza", 9, 8, 6, 6, bando="orco", habilidad="embestida"),
    Carta("Senor de la Guerra Vorg", 10, 9, 8, 7, bando="orco", habilidad="furia"),
    Carta("Muerdehuesos", 7, 6, 5, 6, bando="orco"),
    Carta("Tambor de Guerra", 5, 8, 6, 5, bando="orco", habilidad="furia"),
    Carta("Jabalina Veloz", 6, 5, 9, 4, bando="orco"),
    Carta("Matriarca Gra", 8, 9, 6, 7, bando="orco", habilidad="quema"),
    Carta("Rey Roto", 9, 10, 8, 8, bando="orco"),
    Carta("Porton de Hierro", 4, 8, 5, 6, bando="orco", habilidad="muro"),
    Carta("Mazo Quebrado", 7, 4, 6, 5, bando="orco"),
    Carta("Colmillo Roto", 6, 3, 7, 6, bando="orco"),
    Carta("Gruñido", 5, 6, 4, 7, bando="orco"),
    Carta("Piel Cortada", 4, 5, 8, 5, bando="orco"),
    Carta("Hacha Sucia", 8, 3, 5, 6, bando="orco"),
    Carta("Foso", 5, 4, 7, 7, bando="orco"),
    Carta("Tizón", 3, 7, 6, 7, bando="orco", habilidad="quema"),
    Carta("Aplastador", 8, 7, 5, 6, bando="orco", habilidad="furia"),
    Carta("Cuernos de Guerra", 9, 6, 7, 5, bando="orco", habilidad="embestida"),
    Carta("Espalda Ancha", 6, 8, 7, 6, bando="orco"),
    Carta("Grito de Sangre", 7, 9, 5, 7, bando="orco", habilidad="furia"),
    Carta("Machacador", 9, 7, 6, 8, bando="orco"),
    Carta("Terremoto Verde", 10, 8, 9, 7, bando="orco"),
    Carta("Puño del Cráter", 9, 10, 8, 9, bando="orco", habilidad="furia"),
]

ELFOS_NOCTURNOS = [
    Carta("Espia Umbria", 6, 4, 8, 5, bando="elfo_nocturno"),
    Carta("Hoja Lunar", 4, 8, 5, 9, bando="elfo_nocturno"),
    Carta("Tejedora de Sombras", 3, 9, 6, 7, bando="elfo_nocturno", habilidad="quema"),
    Carta("Centinela Nocturno", 7, 5, 9, 4, bando="elfo_nocturno", habilidad="muro"),
    Carta("Reina de la Noche", 10, 8, 7, 9, bando="elfo_nocturno"),
    Carta("Acechante", 6, 5, 7, 5, bando="elfo_nocturno"),
    Carta("Daga Eclipse", 8, 4, 7, 6, bando="elfo_nocturno"),
    Carta("Oraculo Ciego", 5, 9, 7, 6, bando="elfo_nocturno"),
    Carta("Lanza Penumbra", 9, 6, 8, 5, bando="elfo_nocturno", habilidad="muro"),
    Carta("Principe del Eclipse", 10, 9, 8, 8, bando="elfo_nocturno"),
    Carta("Hermana Umbria", 7, 6, 7, 6, bando="elfo_nocturno", habilidad="furia"),
    Carta("Polilla Negra", 5, 4, 8, 4, bando="elfo_nocturno"),
    Carta("Susurro", 4, 5, 6, 6, bando="elfo_nocturno"),
    Carta("Tinta Viva", 7, 3, 6, 5, bando="elfo_nocturno"),
    Carta("Paso Felpado", 6, 5, 4, 7, bando="elfo_nocturno"),
    Carta("Beso de Sombra", 3, 6, 7, 6, bando="elfo_nocturno", habilidad="quema"),
    Carta("Nido de Búhos", 5, 7, 3, 7, bando="elfo_nocturno"),
    Carta("Velo Gris", 6, 6, 5, 5, bando="elfo_nocturno"),
    Carta("Mirada Hueca", 4, 8, 4, 6, bando="elfo_nocturno"),
    Carta("Puñal de Niebla", 7, 7, 5, 7, bando="elfo_nocturno", habilidad="furia"),
    Carta("Eclipse Parcial", 8, 5, 7, 6, bando="elfo_nocturno", habilidad="embestida"),
    Carta("Canto de Grillo", 6, 8, 6, 7, bando="elfo_nocturno"),
    Carta("Manto de Estrellas", 9, 6, 7, 8, bando="elfo_nocturno", habilidad="furia"),
    Carta("Noche Cerrada", 10, 8, 8, 8, bando="elfo_nocturno"),
    Carta("Vacío Brillante", 9, 9, 8, 9, bando="elfo_nocturno"),
]

HOMBRES_PANTERA = [
    Carta("Acechador", 7, 4, 8, 5, bando="hombre_pantera"),
    Carta("Garra Veloz", 8, 5, 7, 4, bando="hombre_pantera", habilidad="furia"),
    Carta("Saltador", 6, 6, 9, 5, bando="hombre_pantera", habilidad="embestida"),
    Carta("Cazadora Silente", 9, 7, 5, 8, bando="hombre_pantera"),
    Carta("Pantera Alfa", 10, 9, 8, 7, bando="hombre_pantera", habilidad="furia"),
    Carta("Zarpazo", 7, 5, 6, 5, bando="hombre_pantera"),
    Carta("Cola Sigilosa", 6, 7, 5, 6, bando="hombre_pantera"),
    Carta("Ojos Ambar", 5, 8, 7, 5, bando="hombre_pantera"),
    Carta("Salto Mortal", 9, 5, 8, 6, bando="hombre_pantera", habilidad="embestida"),
    Carta("Rey de la Noche", 10, 8, 9, 8, bando="hombre_pantera"),
    Carta("Garra Nocturna", 5, 6, 4, 8, bando="hombre_pantera", habilidad="quema"),
    Carta("Bigote", 5, 4, 8, 4, bando="hombre_pantera"),
    Carta("Rastro Fresco", 4, 5, 6, 6, bando="hombre_pantera"),
    Carta("Ronda Gris", 7, 3, 6, 5, bando="hombre_pantera"),
    Carta("Colmillo Chico", 6, 5, 4, 7, bando="hombre_pantera"),
    Carta("Selva Espesa", 4, 8, 4, 6, bando="hombre_pantera", habilidad="muro"),
    Carta("Juego de Sombras", 3, 6, 7, 6, bando="hombre_pantera", habilidad="quema"),
    Carta("Huella Húmeda", 5, 7, 3, 7, bando="hombre_pantera"),
    Carta("Garra Dividida", 7, 7, 5, 7, bando="hombre_pantera"),
    Carta("Emboscada", 8, 5, 7, 6, bando="hombre_pantera", habilidad="furia"),
    Carta("Caza del Alba", 6, 8, 6, 7, bando="hombre_pantera", habilidad="embestida"),
    Carta("Brinco Letal", 9, 5, 6, 8, bando="hombre_pantera"),
    Carta("Depredador", 9, 6, 8, 7, bando="hombre_pantera"),
    Carta("Noche de Caza", 10, 8, 8, 8, bando="hombre_pantera"),
    Carta("Luna del Jaguar", 9, 9, 8, 9, bando="hombre_pantera"),
]

HOMBRES_LAGARTO = [
    Carta("Escamado", 6, 7, 5, 6, bando="hombre_lagarto", habilidad="muro"),
    Carta("Mordisco Fangoso", 8, 5, 7, 4, bando="hombre_lagarto"),
    Carta("Chaman del Pantano", 4, 9, 5, 8, bando="hombre_lagarto", habilidad="quema"),
    Carta("Cola Acorazada", 7, 8, 6, 5, bando="hombre_lagarto", habilidad="muro"),
    Carta("Senor del Pantano", 10, 8, 9, 7, bando="hombre_lagarto"),
    Carta("Cria Fangosa", 5, 6, 5, 6, bando="hombre_lagarto"),
    Carta("Lanza Juncos", 7, 5, 8, 4, bando="hombre_lagarto"),
    Carta("Curandero Viejo", 5, 8, 7, 6, bando="hombre_lagarto"),
    Carta("Mandibula", 9, 6, 7, 8, bando="hombre_lagarto"),
    Carta("Cocodrilo Anciano", 10, 9, 8, 8, bando="hombre_lagarto"),
    Carta("Guardian del Fango", 7, 7, 5, 8, bando="hombre_lagarto"),
    Carta("Renacuajo", 5, 4, 8, 4, bando="hombre_lagarto"),
    Carta("Barro Tibio", 4, 5, 6, 6, bando="hombre_lagarto"),
    Carta("Junco Verde", 7, 3, 6, 5, bando="hombre_lagarto"),
    Carta("Charco Hondo", 6, 5, 4, 7, bando="hombre_lagarto"),
    Carta("Lengua Rápida", 3, 6, 7, 6, bando="hombre_lagarto"),
    Carta("Nido de Barro", 5, 7, 3, 7, bando="hombre_lagarto"),
    Carta("Piel Húmeda", 6, 6, 5, 5, bando="hombre_lagarto"),
    Carta("Dentellada", 4, 6, 5, 8, bando="hombre_lagarto", habilidad="quema"),
    Carta("Cola del Río", 7, 7, 6, 6, bando="hombre_lagarto", habilidad="furia"),
    Carta("Ciénaga Viva", 8, 5, 7, 6, bando="hombre_lagarto", habilidad="embestida"),
    Carta("Ojos de Pantano", 6, 8, 6, 7, bando="hombre_lagarto"),
    Carta("Triturador", 9, 7, 6, 8, bando="hombre_lagarto"),
    Carta("Pantano Eterno", 10, 8, 8, 8, bando="hombre_lagarto"),
    Carta("Fauces Ancestrales", 9, 9, 8, 9, bando="hombre_lagarto"),
]

TODOS = {
    "humano": HUMANOS,
    "orco": ORCOS,
    "goblin": GOBLINS,
    "elfo": ELFOS,
    "hombre_lobo": HOMBRES_LOBO,
    "vampiro": VAMPIROS,
    "dragon": DRAGONES,
    "elfo_nocturno": ELFOS_NOCTURNOS,
    "hombre_pantera": HOMBRES_PANTERA,
    "hombre_lagarto": HOMBRES_LAGARTO,
}

NOMBRES_BANDO = {
    "humano": "Humanos",
    "orco": "Orcos",
    "goblin": "Goblins",
    "elfo": "Elfos",
    "hombre_lobo": "Hombres Lobo",
    "vampiro": "Vampiros",
    "dragon": "Dragones",
    "elfo_nocturno": "Elfos Nocturnos",
    "hombre_pantera": "Hombres Pantera",
    "hombre_lagarto": "Hombres Lagarto",
}

DESCRIPCION_BANDO = {
    "humano": "Muro, guardia y rey. Pierde duelos largos, gana los cortos.",
    "orco": "Furia por acumulacion: cada vecino aliado la hace mas fuerte.",
    "goblin": "Barato y veloz, con un brujo que quema sin mirar valores.",
    "elfo": "Valores altos en cruz: el Same hace mas dano que la fuerza.",
    "hombre_lobo": "Domina la casilla central y las cadenas de captura.",
    "vampiro": "Equilibrio agresivo, bueno para romper la guardia del rival.",
    "dragon": "Rey de la fuerza bruta: el Quemador rompe el tablero entero.",
    "elfo_nocturno": "Sombras precisas: cruza valores altos y quema desde la oscuridad.",
    "hombre_pantera": "Caza en silencio: furia en grupo y zarpazo en el centro.",
    "hombre_lagarto": "Paciencia acorazada: muros que aguantan y un pantano que traga.",
}